In [5]:
import torch
a = torch.ones(3)
a[1]
float(a[1])
a[2] = 2
a
# 使用.zeros是获取适当大小的数组的一种方法
points = torch.zeros(6)
# 用所需的值覆盖这些0
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points
float(points[0]),float(points[1])
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.shape
points=torch.zeros(3,2)
points
points=torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points[0,1]
points[0]
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
#points.storage()
points_storage = points.storage()
points_storage[0] = 2.0
points.storage()[1]
points
second_point = points[1]
#print(second_point)
second_point.storage_offset()## 获取新张量的存储偏移量
second_point.size()
second_point.shape
points.stride()
second_point.storage_offset()
second_point.stride()
points=torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points_t=points.t()#转置
points_t
id(points.storage()) == id(points_t.storage())
points.stride()
points_t.stride()
some_tensor = torch.ones(3, 4, 5)
#print(some_tensor)
some_tensor.shape
some_tensor.stride()## 获取张量的步幅
some_tensor_t=some_tensor.transpose(0, 2)
#print(some_tensor_t)
some_tensor_t.shape,some_tensor_t.stride()
points.is_contiguous(), points_t.is_contiguous()
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
#print(points)
points_t = points.t()
#print(points_t)
points_t.storage()# 获取张量的底层数据存储
points_t.stride()
points_t_cont = points_t.contiguous()
points_t_cont
points_t_cont.stride()
points_t_cont.storage()#重构

a = torch.ones(3, 2)
a.zero_()
print(a)
#a_t = torch.transpose(a, 0, 1)

a_t = a.transpose(0,1)
print(a_t)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [28]:
#从list(range(9))创建一个张量a，然后预测并验证一下尺寸、偏移和步长。
a = torch.Tensor(list(range(9)))
print(a)
print(a.shape) #尺寸
print(a.storage_offset())#偏移
print(a.stride())#步长
#创建一个张量b = a.view(3, 3)，b[1,1]的值是多少？
b = a.view(3,3)
print(b)
print(b[1,1])
#创建一个张量c = b [1:, 1:]，然后预测并验证一下尺寸、偏移和步长。
c = b[1:,1:]
print(c)
print(a.shape) #尺寸
print(a.storage_offset())#偏移
print(a.stride())#步长
#选择一个余弦或平方根之类的数学运算。你能找到在torch找到正确的对应方法吗？
result =torch.cos(a.float())
#print(result)
a = a.float()
a.cos_()
#你刚刚选择的函数有就地（inplace）版本吗？
#平方根
result = torch.sqrt(a.float())
#print(result)
a = a.float()
a.sqrt_()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])
torch.Size([9])
0
(1,)
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor(4.)
tensor([[4., 5.],
        [7., 8.]])
torch.Size([9])
0
(1,)


tensor([1.0000, 0.7351,    nan,    nan,    nan, 0.5326, 0.9799, 0.8683,    nan])

In [60]:
#白葡萄酒品鉴
import numpy as np 
import csv
wine_path = "/Users/mac/Documents/GitHub/test/winequality-white.csv"

wineq_numpy = np.loadtxt(wine_path, dtype=np.float32,delimiter=',', skiprows=1)  # skiprows=1 用于跳过标题行（如果有的话）
#wineq_numpy = np.genfromtxt(wine_path, delimiter=',', skip_header=1)  # skip_header=1 用于跳过标题行（如果有的话）

#wineq_nump = pd.read_csv(wine_path)
wineq_numpy
#wineq_nump.head()

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [61]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality'])

In [62]:
wineq = torch.from_numpy(wineq_numpy)
wineq.shape,wineq.type()

(torch.Size([4898, 12]), 'torch.FloatTensor')

In [110]:
data = wineq[:,:-1]
data,data.shape
#print(wineq)
target = wineq[:,-1].long() #获取最后一列 葡萄酒质量分数
#print(target)

target_onehot = torch.zeros(target.shape[0],10)
#print(target_onehot)
target_onehot.scatter_(1,target.unsqueeze(1),1.0)
#print(target)
target_unsqueeze = target.unsqueeze(1) #横的tensor变竖的
target_unsqueeze

data_mean = torch.mean(data,dim = 0)#平均值 dim = 0表示沿维数0进行计算
data_mean
data_var = torch.var(data,dim=0)#标准差
#归一化
data_normalized = (data - data_mean)/torch.sqrt(data_var)
data_normalized

bad_indexes = torch.le(target,3)
bad_indexes.shape,bad_indexes.dtype,bad_indexes.sum()#只有20个元素小于3

bad_data = data[bad_indexes]
bad_data.shape

bad_data = data[torch.le(target,3)]#le <=
# 对于numpy数组和PyTorch张量，＆运算符执行逻辑和运算
mid_data = data[torch.gt(target,3) & torch.lt(target,7)] #gt > lt<
good_data = data[torch.ge(target,7)]#ge >=
bad_mean = torch.mean(bad_data,dim = 0)#平均值 dim = 0表示沿维数0进行计算
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)
#print(bad_mean)
#print(mid_mean)
#print(good_mean)
for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))

total_sulfur_threshold = 141.83
#print(total_sulfur_threshold)
total_sulfur_data = data[:,6]
#print(total_sulfur_data)
predicted_indexes = torch.lt(total_sulfur_data, total_sulfur_threshold)
predicted_indexes.shape, predicted_indexes.dtype, predicted_indexes.sum()

actual_indexes = torch.gt(target, 5)
actual_indexes.shape, actual_indexes.dtype, actual_indexes.sum()

n_matches = torch.sum(actual_indexes & predicted_indexes).item()#item作用 取出tensor(3)里的3
#print(n_matches)
n_predicted = torch.sum(predicted_indexes).item()
#print(n_predicted)
n_actual = torch.sum(actual_indexes).item()
#print(n_actual)
n_matches, n_matches / n_predicted, n_matches / n_actual
#有大约2,000例葡萄酒预测对了！因为预测有大约2700例（高品质）葡萄酒，所以有74％的可能性确实是高品质的。不幸的是，实际有约3200例优质葡萄酒，仅预测出了61％。好吧，我们猜你已经知道了，这个结果仅比随机猜要好一点点。

#当然，这个例子太天真了。你可以肯定地知道，葡萄酒的质量受多个变量影响，并且，这些变量的值与质量（可能是实际得分，而不是好/坏这种二值）之间的关系很可能比简单的单个值的阈值更复杂。

#实际上，一个简单的神经网络就将克服所有这些缺点，就像许多其他基本的机器学习方法一样。在完成第5章和第6章后，你将拥有解决此问题的工具，在第5章中，你将从头开始构建第一个神经网络。
    

 0 fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality   7.60   6.89   6.73
3258


(2018, 0.74000733406674, 0.6193984039287906)