In [5]:
import torch
a = torch.ones(3)
a[1]
float(a[1])
a[2] = 2
a
# 使用.zeros是获取适当大小的数组的一种方法
points = torch.zeros(6)
# 用所需的值覆盖这些0
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points
float(points[0]),float(points[1])
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.shape
points=torch.zeros(3,2)
points
points=torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points[0,1]
points[0]
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
#points.storage()
points_storage = points.storage()
points_storage[0] = 2.0
points.storage()[1]
points
second_point = points[1]
#print(second_point)
second_point.storage_offset()## 获取新张量的存储偏移量
second_point.size()
second_point.shape
points.stride()
second_point.storage_offset()
second_point.stride()
points=torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points_t=points.t()#转置
points_t
id(points.storage()) == id(points_t.storage())
points.stride()
points_t.stride()
some_tensor = torch.ones(3, 4, 5)
#print(some_tensor)
some_tensor.shape
some_tensor.stride()## 获取张量的步幅
some_tensor_t=some_tensor.transpose(0, 2)
#print(some_tensor_t)
some_tensor_t.shape,some_tensor_t.stride()
points.is_contiguous(), points_t.is_contiguous()
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
#print(points)
points_t = points.t()
#print(points_t)
points_t.storage()# 获取张量的底层数据存储
points_t.stride()
points_t_cont = points_t.contiguous()
points_t_cont
points_t_cont.stride()
points_t_cont.storage()#重构

a = torch.ones(3, 2)
a.zero_()
print(a)
#a_t = torch.transpose(a, 0, 1)

a_t = a.transpose(0,1)
print(a_t)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [28]:
#从list(range(9))创建一个张量a，然后预测并验证一下尺寸、偏移和步长。
a = torch.Tensor(list(range(9)))
print(a)
print(a.shape) #尺寸
print(a.storage_offset())#偏移
print(a.stride())#步长
#创建一个张量b = a.view(3, 3)，b[1,1]的值是多少？
b = a.view(3,3)
print(b)
print(b[1,1])
#创建一个张量c = b [1:, 1:]，然后预测并验证一下尺寸、偏移和步长。
c = b[1:,1:]
print(c)
print(a.shape) #尺寸
print(a.storage_offset())#偏移
print(a.stride())#步长
#选择一个余弦或平方根之类的数学运算。你能找到在torch找到正确的对应方法吗？
result =torch.cos(a.float())
#print(result)
a = a.float()
a.cos_()
#你刚刚选择的函数有就地（inplace）版本吗？
#平方根
result = torch.sqrt(a.float())
#print(result)
a = a.float()
a.sqrt_()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])
torch.Size([9])
0
(1,)
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor(4.)
tensor([[4., 5.],
        [7., 8.]])
torch.Size([9])
0
(1,)


tensor([1.0000, 0.7351,    nan,    nan,    nan, 0.5326, 0.9799, 0.8683,    nan])

In [60]:
#白葡萄酒品鉴
import numpy as np 
import csv
wine_path = "/Users/mac/Documents/GitHub/test/winequality-white.csv"

wineq_numpy = np.loadtxt(wine_path, dtype=np.float32,delimiter=',', skiprows=1)  # skiprows=1 用于跳过标题行（如果有的话）
#wineq_numpy = np.genfromtxt(wine_path, delimiter=',', skip_header=1)  # skip_header=1 用于跳过标题行（如果有的话）

#wineq_nump = pd.read_csv(wine_path)
wineq_numpy
#wineq_nump.head()

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [61]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality'])

In [62]:
wineq = torch.from_numpy(wineq_numpy)
wineq.shape,wineq.type()

(torch.Size([4898, 12]), 'torch.FloatTensor')

In [66]:
data = wineq[:,:-1]
data,data.shape

target = wineq[:,-1].long()
target

target_onehot = torch.zero(torch.shape(target)
                           )

tensor([6, 6, 6,  ..., 6, 7, 6])